# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: Validate Code

on:
  - workflow_call
  - workflow_dispatch

jobs:
  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Project
        uses: ./.github/actions/setup
      - name: Format Check
        id: format-check
        run: bun run format-check
  type_check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Project
        uses: ./.github/actions/setup
      - name: Type Check
        id: type-check
        run: bun run type-check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Project
        uses: ./.github/actions/setup
      - name: Lint
        id: lint
        run: bun run lint
  test:
    name: Test All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Project
        uses: ./.github/actions/setup
      - name: Run All Tests
        id: test
        run: bun test
